# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identify', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=14)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
